#!/usr/bin/env node
var path = require('path');
var Gasp = require('../gasp');


config = {
	templates: path.join(__dirname, 'templates'),
	output: path.join(__dirname, 'public')
};

var app = new Gasp(config);
app.run();
